services:
  db:
    container_name: cwcpostres
    image: postgres
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env.docker
    environment:
      PGADMIN_DEFAULT_EMAIL: mstommes@gmail.com
      PGADMIN_DEFAULT_PASSWORD: testing
   
  # web:
  #   build: .
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["python", "app.py"]